services:
  rust-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: prod
#    image: portabase/agent:latest
    container_name: rust-prod
    volumes:
      - ./databases.json:/config/config.json
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      LOG: info
      TZ: "Europe/Paris"
      #DATABASES_CONFIG_FILE: "config.toml"
      EDGE_KEY: "<to complete>"
    extra_hosts:
      - "localhost:host-gateway"
    networks:
      - portabase

networks:
  portabase:
    name: portabase_network
    external: true